[package]
name = "primoria"
version = "0.1.0"
edition = "2021"

# to not get errors from rust-analyser
[[bin]]
name = "primoria"
path = "src/main.rs"
test = false
doctest = false
bench = false

[dependencies]
bootloader = "0.9"